environment:
  nuget_apikey:
    secure: GuIAUD0WaG8yqjfDRvds1Yl4znPS7TAuScD/dQ1SwbSGYsCnUk8tLjVUhP0YOr3G
image: WMF 5
install:
  - ps: .\buildscripts\install.ps1
build_script:
  - ps: .\buildscripts\build.ps1
after_test:
  - ps: .\buildscripts\publish.ps1
